const colors = [
  "black",
  "white",
  "gray",
  "red",
  "orange",
  "yellow",
  "green",
  "teal",
  "blue",
  "indigo",
  "purple",
  "pink",
];

module.exports = {
  breakpoints: ["screens"],
  colors: ["colors"],
  spacing: ["spacing"],
  borders: ["borderColor", "borderRadius", "borderWidth"],
  effects: ["boxShadow", "opacity"],
  layout: ["zIndex"],
  flexbox: ["flex", "flexGrow", "flexShrink", "order"],
  grid: [
    "gridTemplateColumns",
    "gridColumn",
    "gridColumnStart",
    "gridColumnEnd",
    "gridTemplateRows",
    "gridRow",
    "gridRowStart",
    "gridRowEnd",
  ],
  typography: [
    "fontFamily",
    "fontSize",
    "fontWeight",
    "letterSpacing",
    "lineHeight",
  ],
  transitions: [
    "transitionProperty",
    "transitionTimingFunction",
    "transitionDuration",
    "transitionDelay",
  ],
  sizing: ["height", "maxWidth", "maxHeight", "minHeight", "minWidth", "width"],
  transforms: ["scale", "rotate", "skew"],
  svg: ["strokeWidth"],
};
